
name: Test deployment on push to main

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
    branches: ['*']

jobs:

  deploy-test:
    name: deploy
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: cache poetry
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-1.2.2-0

      - name: install poetry
        uses: snok/install-poetry@v1
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-0

      - name: poetry install dependencies
        run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: poetry install project
        run: poetry install --no-interaction

      - name: Deploy to pypi test
        run: |
          poetry config repositories.pypi https://pypi.org/legacy/
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build -r pypi



