
name: boum-api-python-sdk

on:
  push:
    branches:
      - '*'

jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: ["3.10.6"]

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade coverage[toml] tox tox-gh-actions          
          python -m pip install --upgrade twine
          python -m pip install -r requirements.txt   

      - name: Build and publish Boum Python Package
        run: |
          python setup.py sdist bdist_wheel --universal
          python -m twine upload --repository $PYPI_REPOSITORY dist/* --username $PYPI_USERNAME --password $PYPI_PASSWORD --skip-existing

    env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD}}
        PYPI_REPOSITORY: ${{ secrets.PYPI_REPOSITORY}}


